### ISSUE TITLE
Odd power delay issue

### ISSUE THREAD

**Issue by KelticDanor** [libsidplayfp/libsidplayfp#82]
I'm unsure if it is me doing something wrong or not but I got a report related to the powerOnDelay and this song \MUSICIANS\L\Lead\Paradise.sid.

When the powerOnDelay is set to 16 or higher the sid tune plays just fine. However on 15 or under it cuts out after half a second or so and I'm uncertain why as even when set to 0 I have never encountered it happening before.

**Comment by drfiemost** [comment]
Yes, it's a known issue, see 5353430
I think it has something to do with the VIC II status at startup (https://sourceforge.net/p/sidplay-residfp/bugs/19/#8a12)

**Comment by KelticDanor** [comment]
Ah I see, sorry about that I didn't realise it was an known one. 👍

**Comment by drfiemost** [comment]
As mentioned here https://github.com/libsidplayfp/libsidplayfp/discussions/95#discussioncomment-7455572 it would be nice to start the sound production only after the initialization is complete. This would also get rid of the volume click. Not sure how to implement this, it would require some kind of hook or something.

**Comment by drfiemost** [comment]
Thinking about this maybe we could clock the emulation for some cycles while discarding the samples.
Something along these lines:
```diff
--- a/src/player.cpp
+++ b/src/player.cpp
@@ -385,6 +385,15 @@ bool Player::config(const SidConfig &cfg, bool force)
     // Update Configuration
     m_cfg = cfg;
 
+    // Run for some cycles until the initialization routine is done
+    for (int i=0; i<10000; i++)
+    {
+        m_c64.clock();
+
+        m_mixer.clockChips();
+        m_mixer.resetBufs();
+    }
+
     return true;
 }
 
```

**Comment by KelticDanor** [comment]
I updated my plugin stuff up to 2.12.0 today and decided to give the above a try, but it appeared to just lock things up. Didn't crash or anything just kind of froze, I know that's probably not the most helpful information but I'd be happy to give it another shot! 👍

**Comment by drfiemost** [comment]
That wasn't supposed to hang :/
Anyway I've commited a better version that removes the startup click but still not fixes the issue:
https://github.com/libsidplayfp/libsidplayfp/commit/3be8ff73450f6168aea18f0bb05a240dde729988

Next steps are:
* run the emulation for some random cycles after poweron/reset
* remove the delay from the init routine
* run the emulation silently until the init routine is done
